network/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from .views import DeleteCommentView,SearchView,follow_user,unfollow_user

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutPage.as_view(), name='logout'),
    path('create_post/', views.CreatePostView.as_view(success_url='/'), name='addpost'),
    path('home/profile/<int:pk>', views.Profile.as_view(), name='profile'),
    path('delete/<int:pk>',views.BbDeleteView.as_view(), name='delete'),
    path('post/<int:pk>/toggle_like/', views.ToggleLikeView.as_view(), name='toggle_like'),
    path('post/<int:pk>/add_comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('home/delete_comment/<int:pk>/', DeleteCommentView.as_view(), name='delete_comment'),
    path('search/', SearchView.as_view(), name='search'),
    path('home/profileuser/<int:pk>',views.ProfileUSer.as_view(),name='profileuser'),
    path('follow/<int:user_id>/', follow_user, name='follow'),
    path('unfollow/<int:user_id>/', unfollow_user, name='unfollow'),
    path('addaboutuser/<int:pk>/',views.AddAboutInformation.as_view(),name='add_about_user'),
    path('chat/',views.ChatView.as_view(),name='chat'),
    path('start_chat/<int:user_id>/', views.StartChatView.as_view(), name='start_chat'),
    path('chathiden/',views.ChatHidenView.as_view(),name='chathiden'),
    path('message/', views.MasegView.as_view(), name='message'),
    path('chathiden/get_messages/<int:chat_id>/', views.GetMessagesView.as_view(), name='get_messages'),
  
  
   
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('network.urls'))
]

network/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class User(AbstractUser):
    avatar = models.ImageField(upload_to='network/static/img/avatar/', null=True, blank=True)
    about = models.CharField(max_length=100,null=True,blank=True)
    date_of_birth = models.DateField(null=True,blank=True)
    hobby = models.CharField(max_length=30,null=True,blank=True)
    work = models.CharField(max_length=30,null=True,blank=True)
    city = models.CharField(max_length=25,null=True,blank=True)





class Post(models.Model):
    title = models.CharField(max_length=100)
    
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='network/static/img/photo/',null=True,blank=True)

    
    
# class UserProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     avatar = models.ImageField(upload_to='static/img/avatars', null=True, blank=True)
    
#     def __str__(self):
#  
# 
#        return self.user.username

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    body = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)


class Follow(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    following = models.ManyToManyField(User,related_name='following')
    followers = models.ManyToManyField(User,related_name='followers')
    def __str__(self):
        return self.user.username
    

class Chat(models.Model):
    members = models.ManyToManyField(User, related_name='members')
    
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=10000)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)

network/forms.py
from django import forms
from network.models import Comment,Post,User,Message

from django.contrib.auth.forms import UserCreationForm


class Registration(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={
                "class": "input-field"
            }),
            'email': forms.TextInput(attrs={
                "class": "input-field"
            }),
            'password1': forms.TextInput(attrs={
                "class": "input-field"
            })
            

        }

class AddPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','photo']
       
class FileUploadForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['avatar']
        


class ChatForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['body']
       

network/views.py
from django.shortcuts import render
from datetime import datetime
from .forms import Registration,AddPost
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import FileUploadForm,ChatForm
from django.utils.translation import gettext as _
from django.urls import reverse_lazy
from .models import Post, Comment, Like, User,Follow,Chat,Message
from django.views.generic.list import ListView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,RedirectView
from django.urls import reverse
from django.http import request
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.views import View
import json
from rest_framework.permissions import IsAuthenticated  
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
# Create your views here.
from rest_framework.views import APIView

class RegistrationView(CreateView):
    form_class = Registration
    template_name = 'registration.html'
    success_url = reverse_lazy('login')
    



class HomeView(LoginRequiredMixin, ListView):
    template_name = 'index.html'
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        user = self.request.user
        following_users = Follow.objects.filter(user=user).values('following')
        queryset = super().get_queryset().filter(user__in=following_users) | super().get_queryset().filter(user=user)
        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_info = User.objects.get(username=self.request.user.username)  # або User.objects.get(id=self.request.user.id)

        context['user_info'] = user_info
        return context





class Login(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True


class LogoutPage(LogoutView):
    pass



class CreatePostView(CreateView):
    model = Post
    form_class = AddPost
    template_name = 'post.html'
    success_url = '/'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

   
# class PostView(TemplateView):
#     template_name = 'posts.html'

#     def post(self, request,**kwargs):
#         data = request.POST
#         user = self.request.user
#         post = Post.objects.get(id=self.kwargs['pk'])
#     success_url = reverse_lazy('home')

# class Profile(UpdateView):
#     form_class = FileUploadForm
#     template_name= 'profile.html'
#     model = User
    
#     def form_valid(self, form,**kwargs):
#         form.instance.user = self.request.user
#         return super().form_valid(form)
    
#     success_url = reverse_lazy('profile', kwargs={'pk': pk})
class AddAboutInformation(UpdateView):
    fields = ['about','date_of_birth','hobby','work','city']
    template_name = 'profile.html'
    model = User

    def get_success_url(self):
        return f'/home/profile/{self.kwargs["pk"]}'

class Profile(UpdateView):
    # form_class = FileUploadForm
    fields = ['avatar']
    template_name = 'profile.html'
    model = User
    
    def test_func(self):
        user_id = self.kwargs['pk']
        return self.request.user.id == int(user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        user = User.objects.get(id=user_id)
        posts = Post.objects.filter(user=user)
        current_user_posts = Post.objects.filter(user=self.request.user)
        followers = Follow.objects.filter(user=user)
        context['user'] = user
        context['posts'] = posts
        context['current_user_posts'] = current_user_posts
        context['followers'] = followers
        return context
    
    def get_success_url(self):
        return f'/home/profile/{self.kwargs["pk"]}'
    
   
    

class BbDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('home')
    template_name = 'index.html'
   





class ToggleLikeView(View):
    def post(self, request, **kwargs):
        data = request.POST
        user = self.request.user
        post = get_object_or_404(Post, id=self.kwargs['pk'])

        if 'like' in data.keys():
            try:
                like = Like.objects.get(user=user, post=post)
                like.delete()
                is_like = False
            except Like.DoesNotExist:
                like = Like(user=user, post=post)
                like.save()
                is_like = True

            like_count = Like.objects.filter(post=post).count()
            return JsonResponse({'like_count': like_count, 'is_like': is_like}, safe=False)

        if 'is_like' in data.keys():
            is_like = Like.objects.filter(user=user, post=post).exists()
            return JsonResponse({'is_like': is_like}, safe=False)




class AddCommentView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs['pk']
        comment_body = request.POST.get('text', '')
        post = Post.objects.get(pk=post_id)
        user = request.user
        comment = Comment.objects.create(body=comment_body, user=user, post=post)

        # Отримати ім'я користувача
        if user.is_authenticated:
            username = user.username
        else:
            username = 'Anonymous'  # або будь-яке значення, яке ви вважаєте за потрібне

        # Повернути дані коментаря у форматі JSON
        data = {
            'id': comment.id,
            'body': comment.body,
            'username': username
        }

        return JsonResponse(data)

class DeleteCommentView(DeleteView):
    model = Comment
    success_url = reverse_lazy('home')
    template_name = 'index.html'




class SearchView(ListView):
    model = User
    template_name = 'index.html'
    context_object_name = 'results'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            return User.objects.filter(username__icontains=query)
        return User.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query')
        return context


class ProfileUSer(TemplateView):
    template_name = 'profileuser.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        user = User.objects.get(id=user_id)
        user_following = Follow.objects.filter(user=self.request.user, following=user).exists()
        posts = Post.objects.filter(user=user)
        followers = Follow.objects.filter(user=self.request.user, following=user)
        user_info = User.objects.get(id=user_id)
        context['user'] = user
        context['user_following'] = user_following
        context['posts'] = posts
        context['followers'] = followers
        context['user_info'] = user_info
        return context
    

def user_profile(request, user_id):
    user = User.objects.get(id=user_id)
    user_following = Follow.objects.filter(user=request.user, following=user).exists()

    context = {
        'user': user,
        'user_following': user_following
    }

    return render(request, 'profileuser.html', context)


def follow_user(request, user_id):
    user = User.objects.get(id=user_id)
    follow, created = Follow.objects.get_or_create(user=request.user)
    follow.following.add(user)

    return redirect('profileuser', pk=user_id)

def unfollow_user(request, user_id):
    user = User.objects.get(id=user_id)
    follow = Follow.objects.get(user=request.user)
    follow.following.remove(user)

    return redirect('profileuser', pk=user_id)


class ChatView(TemplateView):
    template_name = 'masenger.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        following = Follow.objects.filter(user=user)
        context['following_users'] = following.values_list('following__username', flat=True)
        context['user'] = user
        chats = Chat.objects.filter(members=user)
        chat_users = []
        for chat in chats:
            members = chat.members.exclude(id=user.id)
            chat_users.extend(members)
        context['chat_users'] = chat_users
        return context
    

class StartChatView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        user = self.request.user
        username = self.request.POST.get('username')  # Отримати ім'я другого користувача з форми
        user1 = get_object_or_404(User, username=username)
       
        for c in Chat.objects.all():
            if user in c.members.all() and user1 in c.members.all():
                print(user, user1, 'iiiiiii')
                self.url = '/chat'
                break
        else:
            print(user, user1, "yyy")
            chat = Chat()
            chat.save()
            chat.members.add(user, user1)
            self.url = '/chat'
        return super().get_redirect_url(*args, **kwargs)


class ChatHidenView(TemplateView):
    template_name = 'masenger.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        following = Follow.objects.filter(user=user)
        context['following_users'] = following.values_list('following__username', flat=True)
        context['user'] = user
        chats = Chat.objects.filter(members=user)
        chat_users = []
        chat_ids = []  # Збереження ідентифікаторів чатів

        for chat in chats:
            members = chat.members.exclude(id=user.id)
            chat_users.extend(members)

network/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page -->
    <title>Login Forms</title>

    <!-- Main CSS -->
    

    <style>
        /* Custom CSS */
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            padding: 0;
            background: linear-gradient(to left bottom, blue, pink);
            
        }
        
        .title {
            font-family: "Gunny Rewritten", sans-serif;
            text-align: center;
            margin-top: -100px;
        }
        .input-field {
            border: 1px solid rgb(107, 104, 104);
        }
        #wrapper {
            font-family: "Gunny Rewritten", sans-serif;
            border: 2px solid black;
            padding: 70px;
            border-radius: 4%;
            background: linear-gradient(to left bottom, rgb(113, 113, 222), rgb(241, 192, 200));
        }
    </style>
</head>

<body>
    <div class="background-container"></div>
    <div class="center-wrapper">
        <h2 class="title">Login Form</h2>
        <form class="wrapper" method="POST">
            {% csrf_token %}
            <div class="row row-space">
                <div class="col-2">
                    <div class="wrapper" id="wrapper">
                        {% for field in form %}
                            {{ field.errors }}
                            <p>{{ field.label_tag }}<br> {{ field }}</p><br>
                        {% endfor %}
                        <input class="btn btn-secondary" type="submit" value="Log In">
                        
                    </div>
                    
                </div>
                
            </div>
           
        </form>
        <a href="registration/">Sin up</a>
    </div>
</body>

</html> 

network/templates/post.html
<style>
    /* Custom CSS */
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        padding: 0;
        background: linear-gradient(to left bottom, blue, pink);
    }
    
    .title {
        font-family: "Gunny Rewritten", sans-serif;
        text-align: center;
        margin-top: -100px;
    }
    
    .input-field {
        border: 1px solid rgb(107, 104, 104);
    }
    
    #wkk {
        font-family: "Gunny Rewritten", sans-serif;
        border: 2px solid black;
        padding: 70px;
        border-radius: 4%;
        background: linear-gradient(to left bottom, rgb(113, 113, 222), rgb(241, 192, 200));
        position: relative;
    }
    
    .button {
        position: absolute;
        bottom: 20px;
        left: 50%;
        transform: translateX(-50%);
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

<div id="wkk">
    <table>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_table }}
        </form>
    </table>
    <button class="btn btn-secondary button">Create</button>
</div>

network/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/post.js"></script>
    
</head>
<body>
<h2>{{ post.title }}</h2>
<p>{{ post.body }}</p>
<h5>{{ post.user.username }}</h5>
<a id="like" data-url="/post{{ post.id }}/"><img id="img" src="" width="50"></a><p id="likes">{{ like_amount }}</p>

<div id="comments">
    {% for c in comments %}
    <p id='c.id' class="comment">{{ c.user.username }}<br>{{ c.body }}</p>
    {% endfor %}
</div>

    {% csrf_token %}
    <input type="text" id="id_body">
    <button id="add" data-url="/post{{ post.id }}/">Add</button>

</body>
</html>

network/templates/profileuser.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<!-- <script src="/static/js/code.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<link rel="stylesheet" href="/static/css/style.css">


<link rel="stylesheet" href="/static/css/lightbox.min.css">
<script type="text/javascript" src="/static/css/lightbox-plus-jquery.min.js"></script>



 -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
 <link rel="stylesheet" href="/static/css/reg.css">
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
 <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
 <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">  
 <script src="/static/js/code.js"></script>
 
 <!------------------LIght BOx for Gallery--------------> 
 <link rel="stylesheet" href="/static/css/lightbox.min.css">
 <script type=" " src="/static/js/code.js"></script>
 <!------------------LIght BOx for Gallery-------------->

<title>Application</title>
</head>
<body>



    <!-------------------------------NAvigation Starts------------------>

    <style>
      .navbar-nav {
          flex-grow: 1;
          display: flex;
          justify-content: flex-start;
      }
  
      .navbar-btn {
          margin-right: 40px;
       
      }
      .followers {
        margin-bottom: -1%;
        margin-right: 40px;
      }
  </style>
  
  <nav class="navbar navbar-expand-md navbar-dark" style="background-color:#44a6df">
    <a href="/home/" class="navbar-brand"><img src="/static/img/base/logo.png" alt="logo" class="img-fluid" width="70px" height="90px"></a>
  
      <button class="navbar-toggler" data-toggle="collapse" data-target="#responsive"><span class="navbar-toggler-icon"></span></button>
  
      <div class="collapse navbar-collapse" id="responsive">
          <ul class="navbar-nav text-capitalize">
              <li class="nav-item"><a href="/home/" class="nav-link active" onclick="redirectHome(event)">home</a></li>
              
              
          </ul>
          
      <div class="followers">
      <p class="fw-bold"> Followers: {{ followers.count }}</p>
      </div>
          
          <div class="navbar-btn">
              {% if user_following %}
                  <form action="{% url 'unfollow' user.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-link p-0"><img src="/static/img/base/check.png" width="35px"></button>
                  </form>
              {% else %}
                  <form action="{% url 'follow' user.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-link p-0"><img src="/static/img/base/add-friend.png" width="35px"></button>
                  </form>
              {% endif %}
          </div>
      </div>

  
  
  
  
 
  
 
  


                {% load static %}
                                                            
            
{% if user.avatar %}
  <img src="{{ user.avatar.url|cut:"network/" }}" class="rounded-circle" width="70px" height="70px" alt="Avatar">
{% else %}
  <img src="{% static 'img/base/default_avatar.png' %}" alt="Default Avatar" width="70px">
{% endif %}



</nav>

       
                

                                                           
            
    
    
<style>
    .center {
        text-align: center;
    }
</style>
    
    





<div class="container">
  <div class="row">


      <!--------------------------left columns  start-->

      <div class="col-12 col-lg-3">

          <div class="left-column">


              <div class="card card-left1 mb-4" >
                  
                  <div class="card-body text-center ">
                    <h3>Інформація {{user.username}}</h3>

                  </div>




              </div>


              <div class="card shadow-sm card-left2 mb-4">

                  <div class="card-body">
                      
                          
                          <p class="mb-3 card-title">
                            <i class="fas fa-exclamation-circle"></i> Загальна інформація:<br>
                              
                              {{user_info.about}}
                              
                              
                            
                            </p>

                                <p class="card-text">
                                  <i class="fas fa-calendar-week mr-2"></i>Дата народження:<br>
                                  {{ user_info.date_of_birth}}
                                </p>
                                
                                <p class="card-text">
                                  <i class="fas fa-gamepad"></i> Хобі:</br>
                                  {{user_info.hobby}}
                                </p>
                                
                                <p class="card-text">
                                  <i class="far fa-building mr-2"></i>  Місце роботи:</br>
                                {{user_info.work}}
                                </p>
                                
                                <p class="card-text">
                                  <i class="fas fa-home mr-2"></i>Місто в якому проживає: </br>
                                  {{ user_info.city }}
                                </p>
                        

                  </div>
               




              </div>








</div>

      </div>




  
<div class="center">      
  <h2 class="fs-1" >{{ user.username }}</h2>
  <h4>Пости:</h4>
  {% for post in posts %}
    <div>
      <h5>{{ post.title }}</h5>
      <p>{{ post.body }}</p>
      {% if post.photo %}
        <img src="{{ post.photo.url|cut:"network/" }}" alt="Post Photo" width="500px">
      {% endif %}
      <hr>
    </div>
  {% empty %}
    <p>Немає постів.</p>
  {% endfor %}
  
  
  
  
  
  </div>















<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

network/templates/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page -->
    <title>Au Register Forms by Colorlib</title>

    <!-- Main CSS -->
    

    <style>
        /* Custom CSS */
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            padding: 0;
            background: linear-gradient(to left bottom, blue, pink);
            
        }
        
        .title {
            font-family: "Gunny Rewritten", sans-serif;
            text-align: center;
            margin-top: -100px;
        }
        .input-field {
            border: 1px solid rgb(107, 104, 104);
        }
        #wrapper {
            font-family: "Gunny Rewritten", sans-serif;
            border: 2px solid black;
            padding: 70px;
            border-radius: 4%;
            background: linear-gradient(to left bottom, rgb(113, 113, 222), rgb(241, 192, 200));
        }
        .btn {
            background-color: rgb(106, 106, 205);
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 20px;
            cursor: pointer;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="background-container"></div>
    <div class="center-wrapper">
        <h2 class="title">Registration Form</h2>
        <form class="wrapper" method="POST">
            {% csrf_token %}
            <div class="row row-space">
                <div class="col-2">
                    <div class="wrapper" id="wrapper">
                        {% for field in form %}
                            {{ field.errors }}
                            <p>{{ field.label_tag }}<br> {{ field }}</p><br>
                        {% endfor %}
                        <input class="btn btn-secondary" type="submit" value="Sign Up">
                    </div>
                </div>
            </div>
           
        </form>
        <a href="/">Log in</a>
    </div>
</body>

</html>